language: nix
sudo: true
services:
  - docker
branches:
  only:
  - master
cache:
  timeout: 86400
  directories:
  - /tmp/src/node_modules

script: docker run -it -v $(pwd):/tmp/src -w /tmp/src nixos/nix:1.11 ./travis/build.sh
