version: '2'

services:

  angular-seed:
    build:
      context: .
      dockerfile: ./.docker/angular-seed.development.dockerfile
    command: npm start
    container_name: angular-seed-start
    image: angular-seed
    networks:
      - dev-network
    ports:
      - '5555:5555'

  e2e-tests:
    build:
      context: .
      dockerfile: ./e2e-tests.dockerfile
      args:
        - http_proxy
    image: e2e-tests
    volumes:
        - .:/home/tester/gnss-site-manager
        - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
        - DISPLAY

networks:
  dev-network:
    driver: bridge
